version: "3.8"
services:
  # Application
  app:
    build:
      context: ./docker/services/app
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    extra_hosts:
      - "cos_test:172.16.50.101"
  # Web Server
  web:
    build:
      context: ./docker/services/web
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "80:80"
    extra_hosts:
      - "cos_test:172.16.50.101"
  # Database
  database:
    platform: linux/x86_64
    image: mysql:8.0.25
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      DB_CONNECTION_PGSQL: ${DB_CONNECTION_PGSQL}
      DB_HOST_PGSQL: ${DB_HOST_PGSQL}
      DB_PORT_PGSQL: ${DB_PORT_PGSQL}
      DB_DATABASE_PGSQL: ${DB_DATABASE_PGSQL}
      DB_USERNAME_PGSQL: ${DB_USERNAME_PGSQL}
      DB_PASSWORD_PGSQL: ${DB_PASSWORD_PGSQL}
    ports:
      - "3306:3306"
  # Database Management
  pma:
    image: phpmyadmin:5.1
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=${DB_PORT}
    depends_on:
      - "database"
    ports:
      - "8888:80"
  # Caching
  redis:
    image: redis:alpine
    volumes:
      - ./docker/volumes/redis:/data
    ports:
      - "6379:6379"
  supervisor:
    build:
      context: ./supervisor
      dockerfile: supervisor.dockerfile
    container_name: supervisor
    ports:
      - "6001:6001"
    volumes:
      - ./src:/var/www
    extra_hosts:
      - "cos_test:172.16.50.101"
  # Mailing Server
  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: "none"
    ports:
      - "1025:1025"
      - "8025:8025"
